# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75c23e88a03b3ff4f275412dbf370d102a066df2b3cede2ce48eedc5c47889f9b06093c586657856e251a801e1d0d46975931c70e98f371e94ebc45063c2c9b6

test:
  secret_key_base: e39ad8069419d9e08151b2d61e68f8246e52375945aef11a9c4c5ed586f714f6072010d74c0211bdd27df690b143f4ae9e166b0cfdfa62827c7f6b929fcc26ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
